spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: root
    password: 3202547c
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

